# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xczu17eg-ffvc1760-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/klara/magisterka/magisterka.cache/wt [current_project]
set_property parent.project_path /home/klara/magisterka/magisterka.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/klara/magisterka/magisterka.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  /home/klara/Downloads/mem/mem_seq_readout_gen0.mem
  /home/klara/Downloads/mem/mem_seq_readout_gen5.mem
  /home/klara/Downloads/mem/mem_seq_readout_gen6.mem
  /home/klara/Downloads/mem/mem_seq_readout_gen7.mem
  /home/klara/Downloads/mem/mem_seq_readout_gen3.mem
  /home/klara/Downloads/mem/mem_seq_readout_gen4.mem
  /home/klara/Downloads/mem/mem_seq_readout_gen9.mem
  /home/klara/Downloads/mem/mem_seq_readout_gen1.mem
  /home/klara/Downloads/mem/mem_seq_readout_gen8.mem
  /home/klara/Downloads/mem/mem_seq_readout_gen2.mem
}
read_vhdl -vhdl2008 -library xil_defaultlib {
  /home/klara/magisterka/magisterka.srcs/sources_1/new/types.vhd
  /home/klara/magisterka/magisterka.srcs/sources_1/new/tcam.vhd
  /home/klara/magisterka/magisterka.srcs/sources_1/new/array_of_tcam.vhd
  /home/klara/magisterka/magisterka.srcs/sources_1/new/encoder.vhd
  /home/klara/magisterka/magisterka.srcs/sources_1/new/main.vhd
  /home/klara/magisterka/magisterka.srcs/sources_1/new/array_3D.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top main -part xczu17eg-ffvc1760-2-e -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
